name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - '!renovate/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn

      - run: yarn

      - run: yarn format --check
      - run: npx tsc --noEmit
      - run: yarn lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker build .
