name: release

on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "VERSION=$(npm version --json|jq .graphql -r)" >> $GITHUB_ENV
      - run: docker build -t ghcr.io/bangumi/graphql:${{ env.VERSION }} .

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - run: docker push ghcr.io/bangumi/graphql:${{ env.VERSION }}
