name: release

on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE: 'ghcr.io/${{ github.repository_owner }}/graphql'

    steps:
      - uses: actions/checkout@v3
      - run: echo "VERSION=$(npm version --json|jq .graphql -r)" >> $GITHUB_ENV

      - run: |
          LONG_TAG=${{ hashFiles('yarn.lock') }}

          echo "TAG_HASH=1-${LONG_TAG:0:10}" >> $GITHUB_ENV

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - run: |
          if ! docker pull ${{ env.IMAGE }}:base-${TAG_HASH}; then
            echo "build base docker image"
            docker build -t ${{ env.IMAGE }}:base-${TAG_HASH} -f etc/base.dockerfile .
            docker push ${{ env.IMAGE }}:base-${TAG_HASH}
          fi

          docker tag ${{ env.IMAGE }}:base-${TAG_HASH} base-image
        name: build base docker image

      - name: docker build
        run: docker build -t ${{ env.IMAGE }}:latest -f etc/main.dockerfile .

      - run: docker tag  '${{ env.IMAGE }}:latest' '${{ env.IMAGE }}:${{ env.VERSION }}'
      - run: docker push '${{ env.IMAGE }}:latest'
      - run: docker push '${{ env.IMAGE }}:${{ env.VERSION }}'
